### ISSUE TITLE
Folder trash icon in toolbar when using Breeze Dark theme

### ISSUE THREAD

**Issue by Steinhagen** [NitruxSA/plasma-next-icons#215]
The trash item icon is not correctly displayed in the toolbar when using Breeze Dark: 
![darkthemetrash](https://cloud.githubusercontent.com/assets/4029937/9022552/27485472-3882-11e5-8cb3-c9eb0caaee07.png)

**Comment by DarkknightAK** [comment]
Hi
In the old plasma 5.3 breeze dark there was no places/user-folders-small/user-trash-full icon but now it is there and it will be used. 

BUT when the toolbar is larger in size the user-folder/user-trash-full icon was used because of the size. In your example the small icon should be used so please clone the git and copy the breeze dark icons from the git into your system icon set ( /usr/share/icons/breeze dark ) 

maybe the plasmoid can use the icon user-trash from /places/user-folders.... I understand that in oxygen the icon full looks better, but in breeze an red icon in the toolbar isn't that good.

**Comment by Steinhagen** [comment]
This problem doesn't happen when using the git version of plasma-next.
Thank you for the reply. :)
