### ISSUE TITLE
Toolbar icons for sidebar (Okular)

### ISSUE THREAD

**Issue by DarkknightAK** [NitruxSA/plasma-next-icons#26]
Okular use some toolbar icons (22x22 px) for the sidebar in different sizes (small, normal and large) in kubuntu large was the predifined size and there the icons doesn't look good.

**Comment by UriHerrera** [comment]
Toolbar icons are 22, Okular sidebar is a sidebar not a toolbar *they* should change that, that's a design flaw in the software.

**Comment by staniek** [comment]
@DarkknightAK could you please show the screenshot?

@UriHerrera I am not sure it's all so simple:

- The size is configurable in Icons settings
- Configurability comes from the extra fact that high-dpi screens exist now; here we have a problem with 22 because it's not possible to double the size to 44, just to 32 or 48 - there will be blur, right?
- The size of icons of the sidebar is configurable too: ![](http://i.imgur.com/Ycxz9UI.png)

and this feature comes from the KDE framework, not from the app; that said I am not fan of having it accessible in apps so directly.

**Comment by staniek** [comment]
PS: the screenshot is from KDE Platform 4 Okular.

**Comment by UriHerrera** [comment]
That is still a design oversight in Okular. It's like a sidebar that doesn't know what it wants to be. The buttons in it could perfectly be placed in the toolbar, there's more than enough space there.
==========

No, but the canvas can be expanded to 24 and then scaled to 48, 96.
