### ISSUE TITLE
Input device icons only in settings

### ISSUE THREAD

**Issue by kbroulik** [NitruxSA/plasma-next-icons#31]
The icons for keyboard and mouse are only present as `preferences-desktop-mouse` and `preferences-desktop-keyboard`. The respective `input-mouse` and `input-keyboard` icons are missing, probably true for other input devices as well.

**Comment by UriHerrera** [comment]
Are these icons used anywhere, and if they are, are they used correctly?.

**Comment by kbroulik** [comment]
They are used to denote a mouse or keyboard outside of settings and they are part of the Freedesktop Icon Naming specification (input-mouse, input-keyboard, input-gaming (joystick), input-tablet (graphics tablet))

**Comment by UriHerrera** [comment]
Yes, but I'm asking because those used in system settings are at 32 px, I can't just link to those if the device icons are used somewhere else (like a notification in system tray) where they might be used at a different size.

**Comment by DarkknightAK** [comment]
the input-mouse icon was used in okular in the title bar.
![input-mouse](https://dl.dropboxusercontent.com/u/1642456/vdg/plasma-next-icons-working/devices/sidebars/input-mouse.png)

**Comment by UriHerrera** [comment]
Which is wrong usage.

**Comment by DarkknightAK** [comment]
I know. so we can provide the right icon in the tolbar folder and fill a bug report for okular.

**Comment by UriHerrera** [comment]
We're suppose`d to be removing those icons,

**Comment by DarkknightAK** [comment]
so we don't have to give the developer an icon?

**Comment by UriHerrera** [comment]
No because that only means that the dev. will keep using the same icon because it'll be there.

**Comment by DarkknightAK** [comment]
but when we provide an toolbar icon in the right size. not with the same name. with an toolbar name. or do we have an useful toolbar icon for browse (transform-move)

**Comment by UriHerrera** [comment]
The dev. just needs to change what icon is used there and make a request for it. For example that button is just for moving between pages by dragging them, there already is such an icon like *transform-move*.

**Comment by DarkknightAK** [comment]
ok thanks I understand.

**Comment by staniek** [comment]
> The dev. just needs to change what icon is used there and make a request for it. For example that button is just for moving between pages by dragging them, there already is such an icon like transform-move.

Hmm, In Okular I see "browse" is a mode that deactivates selection tools, and one that's far beyond of functionality of a panning tool for the view. It makes links clickable. When text selection is enabled, browsing is disabled, otherwise I wouldn't be able to select text in a middle of a linked text.

Example:
![](http://i.imgur.com/rfuJStk.png)

My suggestion: it would be great to take advanteage of your design creativeness and find an icon for a "browse" mode. 

Browsing mode isn't necessarily reduced to Okular, you can imagine Calligra's wordprocessing app switched to this mode so the users when done with editing can browse the content, click anchors/TOCs/links. The same applies to documents with disabled editing rights.

If you want we can move this discussion to the VDG forum.

**Comment by UriHerrera** [comment]
It's the same behavior as browsing a site, pressing the scroll wheel button actives the panning function and the cursor is turned to an icon similar to *transform-move*. Otherwise the cursor is the regular angled arrow, which there's also an icon for in *edit-select*.

The primary function of the button is to move around in any direction, *transform-move * fits that perfectly. And besides, the tooltip says *navigation tool* not navigation and selection tool.

**Comment by UriHerrera** [comment]
Guidelines have been published, and developers should read them when placing the icons in their software. This somewhat specific problem of each software UI. The icons provided re not supposed to be used elsewhere, as vague as the freedesktop specification also is.
